### ISSUE TITLE
Improvement : Auto-refresh

### ISSUE THREAD

**Issue by pousterlus** [akiko-pusu/redmine_issue_badge#43]
Hi again,

This plutin is already very good, but I've just had an idea about a feature : Would it be possible to auto-refresh the number in the badge without refreshing the page manually ? With AJAX or something ?

Would be great to have a real realtime counter.
Maybe that's too hard to do though...

-- 
Léo.

**Comment by akiko-pusu** [comment]
Hi, I understand your request above, well :)
But I also don’t want to give some negative impact on performance in case so many users use the same Redmine, because I’ve worked as Redmine administrator for a long time.

Implementation to auto refresh is not so difficult, but handling in case user session is time outed, network error, prevent ajax polling made performance impact are rather difficult for me.

If I try to implement this feature, first task will be that administrator can turn on / off auto refresh on plugin’s setting screen :)

**Comment by pousterlus** [comment]
Hi again,

You're right (again !), I wasn't thinking about the performance impact : it's very important to prevent your plugin from slowing down the whole server or raising errors.

I understand that in case user session timeouts, or network errors, something has to be made to avoid ajax polling for nothing.
And I agree : If that option has to be released one day, an option for the administrator to set the automatic poll time is rather mandatory.

If an evolution brings trouble, maybe that's not so much a good idea...

-- 
Léo.

**Comment by akiko-pusu** [comment]
Hi, if you are interested in evaluating this feature, please see commit: 852e7dc.
Or you can try this branch: feature-43-auto-refresh-badge-counter

**Comment by akiko-pusu** [comment]
Hi, I’ve just released v0.0.5, including this feature.
Polling option is added and you can activate this option from plugin’s setting screen.
By default, this option is disabled and administrator can disabled in case any performance issue.

Also v0.0.5 is even as prototype, so feel free to feedback!
